#CC = cc -framework Foundation
CC = cc -arch x86_64 -arch arm64
LDFLAGS = -framework Foundation
#CFLAGS = -fobjc-arc -g
CFLAGS = -fobjc-arc

OBJ = BookEntry.o listKindleBooks.o
PROG = listKindleBooks
BINDIR = /usr/local/bin

$(PROG): $(OBJ)

.PHONY: clean install
clean:
	rm $(PROG) $(OBJ)

install:
	install $(PROG) $(BINDIR)

# dependencies generated by cc -MM MANUALLY
BookEntry.o: BookEntry.m BookEntry.h
listKindleBooks.o: listKindleBooks.m BookEntry.h

